[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { lines = 0.95, functions = 0.95, statements = 0.95 }
coverageSkipTestFiles = true

[install]
exact = false
saveTextLockfile = true
